[profile.default]
  evm_version = "paris"
  optimizer = true
  optimizer_runs = 100
  via_ir = true
  solc_version = "0.8.26"
  verbosity = 3

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[etherscan]
  mainnet = { key = "${ETHERSCAN_API_KEY}" }
  testnet = { key = "${ETHERSCAN_API_KEY}", chain = "11155111" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
